### ISSUE TITLE
Adding more getters

### ISSUE THREAD

**Issue by ralsei** [alex-hhh/data-frame#8]
Right now, there are various things to set or add things to a data-frame, but no way to get them.

The three most glaring examples, for me, are:
- There is a `df-add-series!`, but no `df-get-series` (to get the _series_, not the _vector_)
- There is a `df-set-sorted!`, but no `df-is-sorted?`, or way to recover a comparison function from a series (like `series-cmpfn` or `df-get-cmpfn`). This is useful for doing your own binary search over a series (outside of `df-index-of` and `df-lookup`, which do this internally)
- Data frames are constructed with an NA value with, for example, `(df-read/csv file #:na "NA")`, but there's no way of getting that NA value is after construction

Most of these are useful for manipulation of data-frames after construction.

**Comment by alex-hhh** [comment]
The overall theme is that the data-frame package evolved instead of being designed.  As such, functions and functionality was added only as I needed it (or I thought I would need it).  This generally explains why some reasonable functionality does not exist. I am open to adding new functions, however, I would like a justification for why they are needed. 

## About `df-get-series`

I wanted to keep the `series` structure private (as opposed to the "series" concept), so `df-get-series` would expose this structure.  I would be interested to know what would you use `df-get-series` for?

## About `df-get-cmpfn`

Similarly , I would like to know what would you use the `df-get-cmpfn` for?  You said it is

> ..  for doing your own binary search over a series (outside of `df-index-of` and `df-lookup`, which do this internally)

Could we update `df-index-of` or `df-lookup` to provide the functionality that you are looking for, or provide additional lookup functions to do what you need?

## About getting the NA value

The data frame package has several functions to deal with NA values: `df-is-na?`, `df-has-na?`, `df-has-non-na?` and `df-count-na`.  Would it be better to provide additional functions on this theme instead of getting the NA value?  However, of all the points above, I think that a `df-series-na-value` function would probably make sense.

**Comment by ralsei** [comment]
So my rationale is that I'm currently working on a library for data manipulation (a bunch of functions `data-frame? -> data-frame?`) built on top of `data-frame` (so this is to data-frame as graphite is to plot). I've run into a couple of issues which have led me to run into this. Whether you want to solve these architecturally somehow, you want to allow users to access things formerly set as private (so getting series), or you simply don't want to bother is entirely up to you.

About `df-get-cmpfn`: the rationale is to get the _range_ that a value appears and not its first occurrence (so in the series `a b b b c`, I would get `1` and `3`). This could probably be another form of `df-index-of`, or a modification of it -- basically, it means binary searching from both ends. I don't know how useful this is outside of some optimizations I'm trying to do while splitting data-frames along a variable and joining data-frames. But if you want to add this (or you want me to add it!) feel free.

As for getting the NA value and getting series: oftentimes during manipulation I end up creating series in a new data-frame that are very similar to the series in the original. For example:
```scheme
  (for ([name (in-list df2-series)])
    (df-add-series! return-df (make-series name #:data (make-vector df1-size #f))))
  (for ([name (in-list (df-series-names df1))])
    (df-add-series! return-df (make-series name #:data (df-select df1 name))))
```
This, unfortunately, loses any properties (like sorting, NA, etc) that the original series in `df1` had. Being able to just copy the entire series over would be useful.

The crux of the above issue is that my vision for data manipulation mostly comprises of functional update (threading data through a "pipeline"), and `data-frame` is almost entirely comprised of mutable update. So almost every operation involves creating a new data-frame (either with `make-data-frame` or `df-shallow-copy`), moving data over in some wrangled form, and then spitting it back out. But since there's no way to introspect the original data-frame in certain ways, sometimes information is lost.

**Comment by alex-hhh** [comment]
More data manipulation functions and data cleanup functionality would be nice to have and I welcome contributions in this area.  Since you have a use case for them, you are in the best position to add them or, at least contribute some functions that would be useful for your tasks.

It sounds like the following functions could be immediately added to data frame (do you want to do a PR for these?)

* a `df-equal-range-index` for getting the range of equal values would be a useful function (maybe it needs a better name?)
* a `df-duplicate-series` function to copy a series with all its properties
